name: Sleep and Succeed
description: Sleeps for a given time (in minutes) and exits successfully
author: 'vtb-wanderers63'

inputs:
  duration:
    description: 'Duration to sleep in minutes'
    required: false
    default: '3'

runs:
  using: "composite"
  steps:
    - run: |
        echo "Sleeping for ${{ inputs.duration }} minute(s)..."
        duration=${{ inputs.duration }}
        sleep $(( duration * 60 ))
        echo "Tamaguchi sleep time accomplished."
      shell: bash